spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc: # https://velog.io/@najiexx/Spring-Boot-3에-Swagger-적용하기springdoc-openapi
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /api-docs

